name:  Post JSON File to Two URLs

on:
  push:
    branches: 
      - main # Runs only when pushing to the main branch
  workflow_dispatch: #Allows manual trigger

jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositor
        uses: actions/checkout@v3

      - name: Send JSON Data to First URL
        run: |
         curl -X POST "https://:_rpPDtXcTeqae03MxNCPeQ@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:VhbYXUIMRSeXrgGrYuffUw/streams/AQAAAB4tVa-SLUq5tP4HGoWNog0AAAAA" \
             -H "Content-Type: application/json" \
             -d @stream.json

      - name: Send JSON Data to Second URL
        run: |
         curl -X POST "https://:yeLYNo49Q5quUfcht35wjg@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:VhbYXUIMRSeXrgGrYuffUw/streams/AQAAAH6VYPqs5kT3q_D9E3EExrEAAAAA" \
             -H "Content-Type: application/json" \
             -d @stream.json
             
